import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/fonts.toml",
    "~/.config/alacritty/keymaps.toml",
    "~/.config/alacritty/window.toml"
]

[cursor.style]
blinking = "Off"
shape = "Block"

[scrolling]
history = 100000
